### ISSUE TITLE
About the dataset in ScribbleDA.

### ISSUE THREAD

**Issue by lichen14** [KCL-BMEIS/ScribbleDA#2]
Thank you for a very meaningful work, ScribbleDA.
I am writing to inquire about the dataset used in the paper, Vestibular Schwanomma (VS).
It seems that I did not find the relevant data on the Internet. Can you share the relevant information? Or make this data set public? 
Thank you very much!
![image](https://user-images.githubusercontent.com/25859465/111993046-1ec87e80-8b51-11eb-92e5-34abd9c741f4.png)

**Comment by ReubenDo** [comment]
Hello @lichen14,

The dataset is publicly available on TCIA: https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=70229053

We are also organizing crossMoDA, an unsupervised cross-modality Domain Adaptation challenge with the dataset:  https://crossmoda-challenge.ml/. 
Results will be announced at MICCAI 2021.

I hope this helps!
Reuben

**Comment by lichen14** [comment]
Thanks for your reply   :)
